# Generated by Django 4.2.4 on 2023-08-27 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buses', '0002_alter_bus_start_point'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bus',
            name='end_point',
            field=models.CharField(choices=[('Yangon', 'Yangon'), ('Mandalay', 'Mandalay'), ('Taunggyi', 'Taunggyi'), ('Bagan', 'Bagan'), ('Mawlamyine', 'Mawlamyine')], max_length=20),
        ),
        migrations.AlterField(
            model_name='bus',
            name='start_point',
            field=models.CharField(choices=[('Yangon', 'Yangon'), ('Mandalay', 'Mandalay'), ('Taunggyi', 'Taunggyi'), ('Bagan', 'Bagan'), ('Mawlamyine', 'Mawlamyine')], max_length=20),
        ),
    ]
