# Generated by Django 4.2.4 on 2023-09-01 12:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_bookings_credit_card'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookings',
            old_name='no_of_people',
            new_name='people',
        ),
    ]
