# Generated by Django 4.2.4 on 2023-09-01 13:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('buses', '0003_alter_bus_end_point_alter_bus_start_point'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bookings', '0003_rename_no_of_people_bookings_people'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookings',
            name='bus',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='buses.bus'),
        ),
        migrations.AlterField(
            model_name='bookings',
            name='buyer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
